/**
 * Provider-neutral private object storage port.
 *
 * Business code depends on this interface — never on the AWS SDK or a specific provider.
 * MinIO (local), Cloudflare R2 and AWS S3 are all served by the S3 implementation and differ only
 * in configuration (S3_ENDPOINT, S3_REGION, S3_FORCE_PATH_STYLE, credentials).
 *
 * Objects are always private. Keys are generated by the application (see `objectKeys`); a
 * user-supplied filename is never part of a key.
 */
export interface ObjectStorage {
  /** Resolves when the configured bucket is reachable with the configured credentials. */
  ping(signal?: AbortSignal): Promise<void>;
  /** Stores a private object (overwrites an existing object with the same key). */
  putObject(key: string, body: Uint8Array, options: PutObjectOptions): Promise<void>;
  /**
   * Reads a whole object into memory. Refuses objects larger than `maxBytes` (before downloading
   * them) so a corrupted or unexpected object cannot exhaust memory.
   */
  getObject(key: string, options: { maxBytes: number }): Promise<Uint8Array>;
  /** Deletes an object; deleting a missing object is not an error. */
  deleteObject(key: string): Promise<void>;
}

export interface PutObjectOptions {
  contentType: string;
}

/** Thrown when an object does not exist. */
export class ObjectNotFoundError extends Error {
  constructor(readonly key: string) {
    super('Stored object not found');
    this.name = 'ObjectNotFoundError';
  }
}

/** Thrown when an object exceeds the caller's size limit. */
export class ObjectTooLargeError extends Error {
  constructor(
    readonly key: string,
    readonly size: number,
  ) {
    super('Stored object is larger than allowed');
    this.name = 'ObjectTooLargeError';
  }
}
