/** Audit action names written to `audit_logs.action`. Add new actions here, never inline strings. */
export const AUDIT_ACTIONS = {
  authLoginSuccess: 'AUTH_LOGIN_SUCCESS',
  authLoginFailure: 'AUTH_LOGIN_FAILURE',
  authLogout: 'AUTH_LOGOUT',
  authSessionRevoked: 'AUTH_SESSION_REVOKED',
  authPasswordChanged: 'AUTH_PASSWORD_CHANGED',
  authPasswordResetRequested: 'AUTH_PASSWORD_RESET_REQUESTED',
  authPasswordReset: 'AUTH_PASSWORD_RESET',
  userDisabled: 'USER_DISABLED',
  adminCreated: 'ADMIN_CREATED',
  departmentCreated: 'DEPARTMENT_CREATED',
  departmentUpdated: 'DEPARTMENT_UPDATED',
  departmentStatusChanged: 'DEPARTMENT_STATUS_CHANGED',
  programCreated: 'PROGRAM_CREATED',
  programUpdated: 'PROGRAM_UPDATED',
  programStatusChanged: 'PROGRAM_STATUS_CHANGED',
  academicSessionCreated: 'ACADEMIC_SESSION_CREATED',
  academicSessionUpdated: 'ACADEMIC_SESSION_UPDATED',
  academicSessionStatusChanged: 'ACADEMIC_SESSION_STATUS_CHANGED',
  studentCreated: 'STUDENT_CREATED',
  studentUpdated: 'STUDENT_UPDATED',
  registrationCreated: 'REGISTRATION_CREATED',
  registrationUpdated: 'REGISTRATION_UPDATED',
  registrationStatusChanged: 'REGISTRATION_STATUS_CHANGED',
  studentImportCreated: 'STUDENT_IMPORT_CREATED',
  studentImportUploaded: 'STUDENT_IMPORT_UPLOADED',
  studentImportMappingSaved: 'STUDENT_IMPORT_MAPPING_SAVED',
  studentImportValidated: 'STUDENT_IMPORT_VALIDATED',
  studentImportCommitRequested: 'STUDENT_IMPORT_COMMIT_REQUESTED',
  studentImportCommitted: 'STUDENT_IMPORT_COMMITTED',
  studentImportCancelled: 'STUDENT_IMPORT_CANCELLED',
  studentImportFailed: 'STUDENT_IMPORT_FAILED',
  studentImportRetried: 'STUDENT_IMPORT_RETRIED',
  studentActivationCodeIssued: 'STUDENT_ACTIVATION_CODE_ISSUED',
  studentActivationCodeRevoked: 'STUDENT_ACTIVATION_CODE_REVOKED',
  studentActivationFailed: 'STUDENT_ACTIVATION_FAILED',
  studentAccountActivated: 'STUDENT_ACCOUNT_ACTIVATED',
  studentAccountStatusChanged: 'STUDENT_ACCOUNT_STATUS_CHANGED',
  studentLoginSuccess: 'STUDENT_LOGIN_SUCCESS',
  studentLoginFailure: 'STUDENT_LOGIN_FAILURE',
  studentLogout: 'STUDENT_LOGOUT',
  subjectCreated: 'SUBJECT_CREATED',
  subjectUpdated: 'SUBJECT_UPDATED',
  subjectStatusChanged: 'SUBJECT_STATUS_CHANGED',
  curriculumCreated: 'CURRICULUM_CREATED',
  curriculumUpdated: 'CURRICULUM_UPDATED',
  curriculumActivated: 'CURRICULUM_ACTIVATED',
  curriculumArchived: 'CURRICULUM_ARCHIVED',
  curriculumSubjectAdded: 'CURRICULUM_SUBJECT_ADDED',
  curriculumSubjectUpdated: 'CURRICULUM_SUBJECT_UPDATED',
  curriculumSubjectRemoved: 'CURRICULUM_SUBJECT_REMOVED',
  curriculumSubjectsReordered: 'CURRICULUM_SUBJECTS_REORDERED',
  studentCurriculumAssigned: 'STUDENT_CURRICULUM_ASSIGNED',
  historicalDocumentUploaded: 'HISTORICAL_DOCUMENT_UPLOADED',
  historicalDocumentUpdated: 'HISTORICAL_DOCUMENT_UPDATED',
  historicalDocumentPublished: 'HISTORICAL_DOCUMENT_PUBLISHED',
  historicalDocumentWithdrawn: 'HISTORICAL_DOCUMENT_WITHDRAWN',
  historicalDocumentReplaced: 'HISTORICAL_DOCUMENT_REPLACED',
  historicalDocumentAuthenticityReviewed: 'HISTORICAL_DOCUMENT_AUTHENTICITY_REVIEWED',
  historicalDocumentDownloaded: 'HISTORICAL_DOCUMENT_DOWNLOADED',
  historicalDocumentStudentCopyCreated: 'HISTORICAL_DOCUMENT_STUDENT_COPY_CREATED',
  externalExamAppCreated: 'EXTERNAL_EXAM_APP_CREATED',
  externalExamAppUpdated: 'EXTERNAL_EXAM_APP_UPDATED',
  examinationCreated: 'EXAMINATION_CREATED',
  examinationUpdated: 'EXAMINATION_UPDATED',
  examinationOpened: 'EXAMINATION_OPENED',
  examinationArchived: 'EXAMINATION_ARCHIVED',
  examinationReExamApplicationsOpened: 'EXAMINATION_RE_EXAM_APPLICATIONS_OPENED',
  examinationReExamApplicationsClosed: 'EXAMINATION_RE_EXAM_APPLICATIONS_CLOSED',
  reExamFeeRuleCreated: 'RE_EXAM_FEE_RULE_CREATED',
  reExamFeeRuleActivated: 'RE_EXAM_FEE_RULE_ACTIVATED',
  reExamFeeRuleRetired: 'RE_EXAM_FEE_RULE_RETIRED',
  reExamApplicationSubmitted: 'RE_EXAM_APPLICATION_SUBMITTED',
  reExamApplicationFeeAssessed: 'RE_EXAM_APPLICATION_FEE_ASSESSED',
  reExamApplicationCancelled: 'RE_EXAM_APPLICATION_CANCELLED',
  reExamApplicationApproved: 'RE_EXAM_APPLICATION_APPROVED',
  reExamApplicationRejected: 'RE_EXAM_APPLICATION_REJECTED',
  reExamApplicationsExported: 'RE_EXAM_APPLICATIONS_EXPORTED',
  reExamPaymentDestinationCreated: 'RE_EXAM_PAYMENT_DESTINATION_CREATED',
  reExamPaymentDestinationUpdated: 'RE_EXAM_PAYMENT_DESTINATION_UPDATED',
  reExamPaymentDestinationQrUploaded: 'RE_EXAM_PAYMENT_DESTINATION_QR_UPLOADED',
  reExamPaymentDestinationApproved: 'RE_EXAM_PAYMENT_DESTINATION_APPROVED',
  reExamPaymentDestinationActivated: 'RE_EXAM_PAYMENT_DESTINATION_ACTIVATED',
  reExamPaymentDestinationDeactivated: 'RE_EXAM_PAYMENT_DESTINATION_DEACTIVATED',
  reExamPaymentDestinationRetired: 'RE_EXAM_PAYMENT_DESTINATION_RETIRED',
  reExamPaymentStarted: 'RE_EXAM_PAYMENT_STARTED',
  reExamPaymentVoided: 'RE_EXAM_PAYMENT_VOIDED',
  reExamPaymentSubmitted: 'RE_EXAM_PAYMENT_SUBMITTED',
  reExamPaymentVerified: 'RE_EXAM_PAYMENT_VERIFIED',
  reExamPaymentRejected: 'RE_EXAM_PAYMENT_REJECTED',
  reExamPaymentEvidenceViewed: 'RE_EXAM_PAYMENT_EVIDENCE_VIEWED',
  studentProfileRequestSubmitted: 'STUDENT_PROFILE_REQUEST_SUBMITTED',
  studentProfileRequestCancelled: 'STUDENT_PROFILE_REQUEST_CANCELLED',
  studentProfileRequestApproved: 'STUDENT_PROFILE_REQUEST_APPROVED',
  studentProfileRequestRejected: 'STUDENT_PROFILE_REQUEST_REJECTED',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

/** Audit actions about academic records (shown in dashboard / record activity; auth events are not). */
export const ACADEMIC_AUDIT_ACTIONS: readonly AuditAction[] = [
  'DEPARTMENT_CREATED',
  'DEPARTMENT_UPDATED',
  'DEPARTMENT_STATUS_CHANGED',
  'PROGRAM_CREATED',
  'PROGRAM_UPDATED',
  'PROGRAM_STATUS_CHANGED',
  'ACADEMIC_SESSION_CREATED',
  'ACADEMIC_SESSION_UPDATED',
  'ACADEMIC_SESSION_STATUS_CHANGED',
  'STUDENT_CREATED',
  'STUDENT_UPDATED',
  'REGISTRATION_CREATED',
  'REGISTRATION_UPDATED',
  'REGISTRATION_STATUS_CHANGED',
  'STUDENT_IMPORT_COMMITTED',
  'SUBJECT_CREATED',
  'SUBJECT_UPDATED',
  'SUBJECT_STATUS_CHANGED',
  'CURRICULUM_CREATED',
  'CURRICULUM_UPDATED',
  'CURRICULUM_ACTIVATED',
  'CURRICULUM_ARCHIVED',
  'CURRICULUM_SUBJECT_ADDED',
  'CURRICULUM_SUBJECT_UPDATED',
  'CURRICULUM_SUBJECT_REMOVED',
  'CURRICULUM_SUBJECTS_REORDERED',
  'STUDENT_CURRICULUM_ASSIGNED',
];

/** Audit actions about import jobs (metadata holds the import ID and counts — never row content). */
export const IMPORT_AUDIT_ACTIONS: readonly AuditAction[] = [
  'STUDENT_IMPORT_CREATED',
  'STUDENT_IMPORT_UPLOADED',
  'STUDENT_IMPORT_MAPPING_SAVED',
  'STUDENT_IMPORT_VALIDATED',
  'STUDENT_IMPORT_COMMIT_REQUESTED',
  'STUDENT_IMPORT_COMMITTED',
  'STUDENT_IMPORT_CANCELLED',
  'STUDENT_IMPORT_FAILED',
  'STUDENT_IMPORT_RETRIED',
];
